[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[variables]
MODEL_DIR = "/app"
MODEL_BACKEND = "auto"
PYTHONPATH = "/app"

[environments.production.variables]
RAILWAY_ENVIRONMENT_NAME = "production"
