[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.kv]
PORT = "8000"
API_PORT = "8000"
MODEL_DIR = "/app/models"
MODEL_BACKEND = "auto"
PYTHONPATH = "/app"

[[sharedEnvironments]]
project = "hazard-detection"
name = "production"
