[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python app.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
# Ensure service binds to all interfaces
watchPatterns = []

# Environment variables are set directly in Railway dashboard for security

[services.hazard-detection.environments.production]
API_URL = "https://hazard-api-production-production.up.railway.app"
GOOGLE_CALLBACK_URL = "https://hazard-detection-production-8735.up.railway.app/auth/google/callback"

[services.hazard-detection-api.environments.production]
MODEL_DIR = "/app"
MODEL_BACKEND = "auto"
PYTHONPATH = "/app"
PORT = "8080"
API_PORT = "8080"
